project:
  type: website
  output-dir: docs

website:
  title: "Working Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: derivations.qmd
        text: Derivations

format:
  html:
    theme: cosmo
    toc: true
    html-math-method: mathjax